module HospitalApp{

interface HospitalServerInter {



 void bookAppointment (in string patientID, in string appointmentID, in string appointmentType) ;
	
void getAppointmentSchedule (in string patientID);
	
 void cancelAppointment (in string patientID, in string appointmentID);
	

	
 void addAppointment (in string appointmentID, in string appointmentType, in long capacity, in string adminID);
	
 void removeAppointment (in string appointmentID, in string appointmentType, in string adminID);
	
 void listAppointmentAvailability (in string appointmentType);
 
void swapAppointment (in string patientID, in string oldAppointmentID,in string oldAppointmentType,
			in string newAppointmentID, in string newAppointmentType);
	
boolean checkAppointment (in string appointmentType,in string appointmentID,in string patientID);

oneway void shutdown();

};

};