package corba;


/**
* corba/frontEndOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Corba.idl
* Saturday, November 23, 2019 3:54:02 PM EST
*/

public interface frontEndOperations extends frontEndOperationsOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface frontEndOperations
