package corba;

/**
* corba/frontEndOperationsHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Corba.idl
* Saturday, November 23, 2019 1:11:50 PM EST
*/

public final class frontEndOperationsHolder implements org.omg.CORBA.portable.Streamable
{
  public corba.frontEndOperations value = null;

  public frontEndOperationsHolder ()
  {
  }

  public frontEndOperationsHolder (corba.frontEndOperations initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = corba.frontEndOperationsHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    corba.frontEndOperationsHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return corba.frontEndOperationsHelper.type ();
  }

}
