package corba;


/**
* corba/frontEndOperationsOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Corba.idl
* Saturday, November 23, 2019 1:11:50 PM EST
*/

public interface frontEndOperationsOperations 
{
  void bookAppointment (String patientID, String appointmentID, String appointmentType);
  void getAppointmentSchedule (String patientID);
  void cancelAppointment (String patientID, String appointmentID);
  void addAppointment (String appointmentID, String appointmentType, int capacity, String adminID);
  void removeAppointment (String appointmentID, String appointmentType, String adminID);
  void listAppointmentAvailability (String appointmentType);
  void swapAppointment (String patientID, String oldAppointmentID, String oldAppointmentType, String newAppointmentID, String newAppointmentType);
  void shutdown ();
} // interface frontEndOperationsOperations
