package corba;

import java.io.IOException;

/**
* corba/frontEndOperationsOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Corba.idl
* Saturday, November 23, 2019 3:54:02 PM EST
*/

public interface frontEndOperationsOperations 
{
  void bookAppointment (String patientID, String appointmentID, String appointmentType) throws IOException;
  void getAppointmentSchedule (String patientID) throws IOException;
  void cancelAppointment (String patientID, String appointmentID) throws IOException;
  void addAppointment (String appointmentID, String appointmentType, int capacity, String adminID) throws IOException;
  void removeAppointment (String appointmentID, String appointmentType, String adminID) throws IOException;
  void listAppointmentAvailability (String appointmentType) throws IOException;
  void swapAppointment (String patientID, String oldAppointmentID, String oldAppointmentType, String newAppointmentID, String newAppointmentType) throws IOException;
  void shutdown ();
} // interface frontEndOperationsOperations
