package HospitalApp;


/**
* HospitalApp/HospitalServerInter.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from hospitalserver.idl
* Sunday, October 27, 2019 11:26:52 AM EDT
*/

public interface HospitalServerInter extends HospitalServerInterOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface HospitalServerInter
