package HospitalApp;


/**
* HospitalApp/HospitalServerInterOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from hospitalserver.idl
* Sunday, October 27, 2019 11:26:52 AM EDT
*/

public interface HospitalServerInterOperations 
{
  void bookAppointment (String patientID, String appointmentID, String appointmentType);
  void getAppointmentSchedule (String patientID);
  void cancelAppointment (String patientID, String appointmentID);
  void addAppointment (String appointmentID, String appointmentType, int capacity, String adminID);
  void removeAppointment (String appointmentID, String appointmentType, String adminID);
  void listAppointmentAvailability (String appointmentType);
  void swapAppointment (String patientID, String oldAppointmentID, String oldAppointmentType, String newAppointmentID, String newAppointmentType);
  boolean checkAppointment (String appointmentType, String appointmentID, String patientID);
  void shutdown ();
} // interface HospitalServerInterOperations
