package HospitalApp;

/**
* HospitalApp/HospitalServerInterHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from hospitalserver.idl
* Sunday, October 27, 2019 11:26:52 AM EDT
*/

public final class HospitalServerInterHolder implements org.omg.CORBA.portable.Streamable
{
  public HospitalApp.HospitalServerInter value = null;

  public HospitalServerInterHolder ()
  {
  }

  public HospitalServerInterHolder (HospitalApp.HospitalServerInter initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = HospitalApp.HospitalServerInterHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    HospitalApp.HospitalServerInterHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return HospitalApp.HospitalServerInterHelper.type ();
  }

}
