package HospitalApp;


/**
* HospitalApp/HospitalServerInterPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from hospitalserver.idl
* Sunday, October 27, 2019 11:26:52 AM EDT
*/

public abstract class HospitalServerInterPOA extends org.omg.PortableServer.Servant
 implements HospitalApp.HospitalServerInterOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("bookAppointment", new java.lang.Integer (0));
    _methods.put ("getAppointmentSchedule", new java.lang.Integer (1));
    _methods.put ("cancelAppointment", new java.lang.Integer (2));
    _methods.put ("addAppointment", new java.lang.Integer (3));
    _methods.put ("removeAppointment", new java.lang.Integer (4));
    _methods.put ("listAppointmentAvailability", new java.lang.Integer (5));
    _methods.put ("swapAppointment", new java.lang.Integer (6));
    _methods.put ("checkAppointment", new java.lang.Integer (7));
    _methods.put ("shutdown", new java.lang.Integer (8));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // HospitalApp/HospitalServerInter/bookAppointment
       {
         String patientID = in.read_string ();
         String appointmentID = in.read_string ();
         String appointmentType = in.read_string ();
         this.bookAppointment (patientID, appointmentID, appointmentType);
         out = $rh.createReply();
         break;
       }

       case 1:  // HospitalApp/HospitalServerInter/getAppointmentSchedule
       {
         String patientID = in.read_string ();
         this.getAppointmentSchedule (patientID);
         out = $rh.createReply();
         break;
       }

       case 2:  // HospitalApp/HospitalServerInter/cancelAppointment
       {
         String patientID = in.read_string ();
         String appointmentID = in.read_string ();
         this.cancelAppointment (patientID, appointmentID);
         out = $rh.createReply();
         break;
       }

       case 3:  // HospitalApp/HospitalServerInter/addAppointment
       {
         String appointmentID = in.read_string ();
         String appointmentType = in.read_string ();
         int capacity = in.read_long ();
         String adminID = in.read_string ();
         this.addAppointment (appointmentID, appointmentType, capacity, adminID);
         out = $rh.createReply();
         break;
       }

       case 4:  // HospitalApp/HospitalServerInter/removeAppointment
       {
         String appointmentID = in.read_string ();
         String appointmentType = in.read_string ();
         String adminID = in.read_string ();
         this.removeAppointment (appointmentID, appointmentType, adminID);
         out = $rh.createReply();
         break;
       }

       case 5:  // HospitalApp/HospitalServerInter/listAppointmentAvailability
       {
         String appointmentType = in.read_string ();
         this.listAppointmentAvailability (appointmentType);
         out = $rh.createReply();
         break;
       }

       case 6:  // HospitalApp/HospitalServerInter/swapAppointment
       {
         String patientID = in.read_string ();
         String oldAppointmentID = in.read_string ();
         String oldAppointmentType = in.read_string ();
         String newAppointmentID = in.read_string ();
         String newAppointmentType = in.read_string ();
         this.swapAppointment (patientID, oldAppointmentID, oldAppointmentType, newAppointmentID, newAppointmentType);
         out = $rh.createReply();
         break;
       }

       case 7:  // HospitalApp/HospitalServerInter/checkAppointment
       {
         String appointmentType = in.read_string ();
         String appointmentID = in.read_string ();
         String patientID = in.read_string ();
         boolean $result = false;
         $result = this.checkAppointment (appointmentType, appointmentID, patientID);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 8:  // HospitalApp/HospitalServerInter/shutdown
       {
         this.shutdown ();
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:HospitalApp/HospitalServerInter:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public HospitalServerInter _this() 
  {
    return HospitalServerInterHelper.narrow(
    super._this_object());
  }

  public HospitalServerInter _this(org.omg.CORBA.ORB orb) 
  {
    return HospitalServerInterHelper.narrow(
    super._this_object(orb));
  }


} // class HospitalServerInterPOA
