package corbaFrontEnd;


/**
* corbaFrontEnd/frontEndOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Corba.idl
* Saturday, November 23, 2019 4:46:53 PM EST
*/

public interface frontEndOperations extends frontEndOperationsOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface frontEndOperations
