package corbaFrontEnd;


/**
* corbaFrontEnd/frontEndOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Corba.idl
* Wednesday, November 27, 2019 10:00:53 PM EST
*/

public interface frontEndOperations extends frontEndOperationsOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface frontEndOperations
