package corbaFrontEnd;


/**
* corbaFrontEnd/frontEndOperationsHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Corba.idl
* Saturday, November 23, 2019 4:46:53 PM EST
*/

abstract public class frontEndOperationsHelper
{
  private static String  _id = "IDL:corbaFrontEnd/frontEndOperations:1.0";

  public static void insert (org.omg.CORBA.Any a, corbaFrontEnd.frontEndOperations that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static corbaFrontEnd.frontEndOperations extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (corbaFrontEnd.frontEndOperationsHelper.id (), "frontEndOperations");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static corbaFrontEnd.frontEndOperations read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_frontEndOperationsStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, corbaFrontEnd.frontEndOperations value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static corbaFrontEnd.frontEndOperations narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof corbaFrontEnd.frontEndOperations)
      return (corbaFrontEnd.frontEndOperations)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      corbaFrontEnd._frontEndOperationsStub stub = new corbaFrontEnd._frontEndOperationsStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static corbaFrontEnd.frontEndOperations unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof corbaFrontEnd.frontEndOperations)
      return (corbaFrontEnd.frontEndOperations)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      corbaFrontEnd._frontEndOperationsStub stub = new corbaFrontEnd._frontEndOperationsStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
