package corbaFrontEnd;

import java.io.IOException;

/**
* corbaFrontEnd/frontEndOperationsOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Corba.idl
* Wednesday, November 27, 2019 10:00:53 PM EST
*/

public interface frontEndOperationsOperations 
{
  String bookAppointment (String patientID, String appointmentID, String appointmentType) throws IOException; 
  String getAppointmentSchedule (String patientID) throws IOException;
  String cancelAppointment (String patientID, String appointmentID)throws IOException;
  String addAppointment (String appointmentID, String appointmentType, int capacity, String adminID)throws IOException;
  String removeAppointment (String appointmentID, String appointmentType, String adminID)throws IOException;
  String listAppointmentAvailability (String adminID, String appointmentType) throws IOException;
  String swapAppointment (String patientID, String oldAppointmentID, String oldAppointmentType, String newAppointmentID, String newAppointmentType)throws IOException;
  void shutdown ();
} // interface frontEndOperationsOperations
