package corbaFrontEnd;

/**
* corbaFrontEnd/frontEndOperationsHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Corba.idl
* Wednesday, November 27, 2019 10:00:52 PM EST
*/

public final class frontEndOperationsHolder implements org.omg.CORBA.portable.Streamable
{
  public corbaFrontEnd.frontEndOperations value = null;

  public frontEndOperationsHolder ()
  {
  }

  public frontEndOperationsHolder (corbaFrontEnd.frontEndOperations initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = corbaFrontEnd.frontEndOperationsHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    corbaFrontEnd.frontEndOperationsHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return corbaFrontEnd.frontEndOperationsHelper.type ();
  }

}
